# -*- coding: utf-8 -*-
"""RAG LLM Model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZ0-j2MomXtf8_Ut-Ba-mDcNjQ0TCQoy
"""

!nvidia-smi

# STEP 1: INSTALL UPDATED DEPENDENCIES
# Run this cell, then click 'Restart Session' if prompted.

!pip install -U duckduckgo_search requests beautifulsoup4 langchain langchain-community langchain-text-splitters sentence-transformers faiss-cpu transformers accelerate bitsandbytes pynvml torch torchvision

!pip install -q transformers accelerate bitsandbytes
!pip install -q duckduckgo_search
!pip install -q langchain langchain-community
!pip install -q langchain-text-splitters
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q beautifulsoup4 requests

!pip uninstall -y duckduckgo_search
!pip install -q ddgs

# 1. Install specific bitsandbytes version
!pip install -U bitsandbytes

import os
import torch

# 2. Add library paths for CUDA 12/13 stability
os.environ['LD_LIBRARY_PATH'] = '/usr/lib64-nvidia:/usr/local/cuda/lib64' + (':' + os.environ.get('LD_LIBRARY_PATH', '') if os.environ.get('LD_LIBRARY_PATH') else '')

# 3. Verification
try:
    import bitsandbytes as bnb
    print(f"PyTorch CUDA: {torch.cuda.is_available()}")
    print(f"BnB Version: {bnb.__version__}")
    print("✅ Environment paths updated. If you still see errors, please Restart Session once and run this cell again.")
except Exception as e:
    print(f"⚠️ Status: {e}")

import bitsandbytes as bnb
print(f"Current bitsandbytes version: {bnb.__version__}")
if bnb.__version__ < '0.46.1':
    print("❌ VERSION STILL TOO OLD. Please go to 'Runtime' -> 'Restart session' now!")
else:
    print("✅ VERSION OK. You can now run the Chatbot cell below.")

"""### Fix applied
I've updated the `LD_LIBRARY_PATH` and reinstalled `bitsandbytes`. Please run the cell above, and then try running the **🚀 FREE RAG AI CHATBOT** cell again.
"""

import os
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"
os.environ["BITSANDBYTES_NOWELCOME"] = "1"

import torch
import gc
import requests
from bs4 import BeautifulSoup
from ddgs import DDGS
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

# CONFIG
LLM_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

def search_web(query, max_results=3):
    print(f"\n[STEP 1] Searching: {query}...")
    try:
        with DDGS() as ddgs:
            return [r['href'] for r in ddgs.text(query, max_results=max_results)]
    except: return []

def scrape_url(url):
    try:
        res = requests.get(url, timeout=8)
        soup = BeautifulSoup(res.text, "html.parser")
        for s in soup(['script', 'style']): s.decompose()
        return soup.get_text(separator=' ', strip=True)[:4000]
    except: return ""

def load_model():
    print("\n[STEP 4] Loading AI Model...")
    gc.collect()
    torch.cuda.empty_cache()
    try:
        # Simplified config to avoid conversion errors
        bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)
        tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL)
        model = AutoModelForCausalLM.from_pretrained(LLM_MODEL, quantization_config=bnb_config, device_map="auto")
        return pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=150)
    except Exception as e:
        print(f"[ERROR] Model fail: {e}")
        return None

def main():
    q = input("Your Question: ").strip()
    if not q: return

    urls = search_web(q)
    data = " ".join([scrape_url(u) for u in urls if u])

    print("[STEP 3] Processing context...")
    splihowtter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks = splitter.split_text(data)
    db = FAISS.from_texts(chunks, HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL))

    gen = load_model()
    if gen:
        context = "\n".join([d.page_content for d in db.similarity_search(q, k=2)])
        prompt = f"<|system|>\nUse context to answer.\nContext: {context}</s>\n<|user|>\n{q}</s>\n<|assistant|>"
        ans = gen(prompt)[0]['generated_text'].split("<|assistant|>")[-1]
        print(f"\nANSWER:\n{ans}")

if __name__ == "__main__":
    main()



